version: '3'

volumes:
  db-data:

services:
  postgres:
    image: "postgres:alpine"
    volumes:
      - db-data:/pgdata
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: shoppingcart
      POSTGRES_DB: shoppingcart
      POSTGRES_USER: shoppingcart
      PGDATA: /pgdata

  app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: 'true'
      DJANGO_ALLOWED_HOSTS: '*'

      DB_NAME: shoppingcart
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: shoppingcart
      DB_PASSWORD: shoppingcart

      STAGE: local

    stdin_open: true
    tty: true
    command: ["runserver", "0.0.0.0:8000"]
