# Generated by Django 4.1.6 on 2023-02-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0002_shoppingcart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('paid', 'Paid')], default='opened', max_length=6),
        ),
    ]
